# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_auto_20171016_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpersonal',
            name='kids',
            field=models.CharField(choices=[('0', 'NONE'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05')], default='0', max_length=30),
        ),
    ]
